### ISSUE TITLE
Only latest flash message is shown

### ISSUE THREAD

**Issue by philippejadin** [DraperStudio/Laravel-Flash#4] opened 2016-05-18 08:36 UTC
# Issue / Motivation:
I'd like to have multiple flash messages shown at once, only the latest is shown in views

## Expected behavior:

```
flash()->success('You successfully read this important alert message.')
       ->info('This alert needs your attention, but it\'s not super important.')
       ->warning('Better check yourself, you\'re not looking too good.')
       ->error('Change a few things up and try submitting again.')
       ->overlay('One fine body...');

       dd($request);
```

The session should contain multiple flash messages. 

## Actual behavior:
Only the latest flash message "One fien boby" is indeed there

Can you help me ?

**Comment by DraperStudio** [comment] 2016-05-18 09:42
Quick pushed a fix that works local. Try to use the following.

```php
    flash()->success('You successfully read this important alert message.')
           ->info('This alert needs your attention, but it\'s not super important.')
           ->warning('Better check yourself, you\'re not looking too good.')
           ->error('Change a few things up and try submitting again.')
           ->commit();
```

**Comment by philippejadin** [comment] 2016-05-22 08:35
Thank you for this quick reply. Do you think it could be done in a way that doesn't need a commit ? Often you flash various messages in  different places, and return a view at some point, but needing to do a commit "just in case" is less practical.

I suspect you made it this way because of a limitation in laravel session flash handling (not accepting arrays? Or only once?), but I'm not an expert in this :-)

**Comment by DraperStudio** [comment] 2016-05-22 08:47
The issue is that I can only flash one message at a time or an array. With the commit method I flash all messages that are contained in the `$messages` array.

https://github.com/DraperStudio/Laravel-Flash/blob/master/src/FlashNotifier.php#L117-L134

I am still thinking about another solution but can't come up with one now because the Messages have to be flashed via the `flash` for them to be removed on the next request.

**Comment by philippejadin** [comment] 2016-05-22 09:09
I had this other idea : don't use flash at all, and remove a message from the session only when it is effectively displayed in the view. A view helper like foreach (Flash::messages() as $message) would return the messages array and remove it from the session, effectively mimicking the flash behavior (but at the cost of being incompatible with previous releases of your flash utility).

I thought about this, because sometimes a flashed message is lost in a double redirect and never actually shown to the user...

**Comment by DraperStudio** [comment] 2016-05-22 09:23
Could you send a PR for the changes you propose so that I could take a look at it?

**Comment by philippejadin** [comment] 2016-05-23 12:48
This is my very first pull request, so I hope it worked as expected :-)

I finaly found a simplier solution that looks to be working fine

**Closed** 2016-05-24 14:16 UTC
